mod lib;
use lib::Cell;
use lib::Sudoku;

fn main() {
    // Source: https://youtu.be/9m9t8ie9-EE
    // Source: https://cracking-the-cryptic.web.app/sudoku/PrfmJPgdft
    let sudoku = Sudoku::new([
        Cell::new('5'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('2'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('4'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('6'),
        Cell::new(' '),
        Cell::new('3'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('3'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('9'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('7'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('3'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('7'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('7'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('8'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('6'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('2'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('8'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('3'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('4'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('6'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('1'),
        Cell::new(' '),
        Cell::new(' '),
        Cell::new('5'),
        Cell::new(' '),
        Cell::new(' ')
    ]);

    println!("\n== PRETTY OUTPUT ==");
    println!("{}", sudoku);

    println!("\n== POSIBILITIES ==");
    sudoku.debug_posibilities()
}
